# Generated by Django 3.0.7 on 2020-07-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200701_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='title',
        ),
    ]
