# Generated by Django 3.0.7 on 2020-07-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200701_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cp',
            name='cpno',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
