# Generated by Django 3.0.7 on 2020-07-01 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200701_0933'),
        ('reports', '0006_dailyreport_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='pgesco_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgesco_id', related_query_name='pgesco_id', to='account.Account'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title', related_query_name='title', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', related_query_name='created_by', to='account.Account'),
        ),
    ]
