# Generated by Django 3.0.7 on 2020-07-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200701_0933'),
        ('reports', '0007_auto_20200701_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='pgesco_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pgescoid', related_query_name='pgescoid', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usertitle', related_query_name='usertitle', to='account.Account'),
        ),
    ]
