# Generated by Django 3.0.7 on 2020-07-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200701_0933'),
        ('reports', '0010_auto_20200701_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', related_query_name='created_by', to='account.Account'),
        ),
    ]
