# Generated by Django 3.0.7 on 2020-07-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20200703_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportactivity',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
