# Generated by Django 3.0.7 on 2020-07-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_reportactivity_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportactivity',
            name='shift',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='shift',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
