# Generated by Django 3.0.7 on 2020-07-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20200704_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='shift',
            field=models.CharField(blank=True, choices=[('Day', 'Day'), ('Night', 'Night')], max_length=20, null=True),
        ),
    ]
