# Generated by Django 3.0.7 on 2020-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200704_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='daily/user_directory_path/'),
        ),
    ]
