# Generated by Django 3.0.7 on 2020-07-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200717_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path/'),
        ),
    ]
