# Generated by Django 3.0.7 on 2020-07-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200701_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pgesco_Id',
            new_name='user_pgesco_Id',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='title',
            new_name='user_title',
        ),
    ]
