# Generated by Django 3.0.7 on 2020-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200701_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='responsability',
            field=models.IntegerField(default=1),
        ),
    ]
