# Generated by Django 3.0.7 on 2020-07-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_responsability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='responsability',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
